package-lock.json
package.json
src/lib/components/button.svelte
src/lib/components/post.svelte

feat: add support for scss

---

src/lib/components/avatar.svelte
src/lib/components/button.svelte
src/lib/components/header.svelte
src/lib/components/icons/user.svelte
src/lib/components/icons/wallet.svelte
src/lib/components/post.svelte
src/lib/components/wallet-connect.svelte
src/lib/types.ts

feat: expose class on all components

---

src/lib/temp/index.svelte
src/routes/dev/+page.svelte

chore: add more test data and dev page

---

src/lib/components/header.svelte
src/lib/components/wallet-connect.svelte
src/lib/routes.ts
src/routes/+page.svelte
src/routes/post/new/+page.svelte
src/routes/profile/+page.svelte
src/routes/profile/new/+page.svelte
tests/test.ts

feat: use constants for routes instead of hardcoded strings

---

package-lock.json
packages/ui/package.json
packages/ui/src/lib/components/header.svelte
packages/ui/src/lib/components/post.svelte
packages/ui/src/lib/stores/profile.ts
packages/ui/src/routes/+page.svelte
packages/ui/src/routes/post/new/+page.svelte
packages/ui/src/routes/profile/+page.svelte

feat: add sign in with web3 wallet

---

packages/ui/src/lib/components/post.svelte
packages/ui/src/lib/components/wallet-connect.svelte
packages/ui/src/routes/+page.svelte

Use outlines instead of borders on masonry items
Edit wallet-connect.svelte to match masonry
resolves #122

style: fixes borders on masonry items

---

packages/ui/src/lib/components/wallet-connect.svelte
packages/ui/src/routes/+page.svelte

includes small fix to wallet-connect component's bottom-border color on dark mode

style: fix share-freely borders on persona homepage

---

packages/ui/src/lib/components/input-string.svelte
packages/ui/src/lib/components/post.svelte
packages/ui/src/lib/components/wallet-connect.svelte
packages/ui/src/routes/+page.svelte
packages/ui/src/routes/post/new/+page.svelte

- add max-width of 450px
- remove outline
- implement autofocus, currently throwing error

style: input-string component

---

packages/ui/src/routes/profile/+page.svelte

style: add break word to profile hashes (commitment/nullifier/trapdoor) so the page doesn't blow up on mobile

style: add break word to profile hashes

---

packages/ui/src/routes/+page.svelte

feat: add loading state when fetching messages from waku

---

packages/ui/src/lib/components/grid.svelte
packages/ui/src/lib/components/header-top.svelte
packages/ui/src/lib/components/persona.svelte
packages/ui/src/routes/+page.svelte
packages/ui/src/routes/styles.css

Update grid breakpoints according to latest design
Create Grid component
Edit header-top to match grid breakpoints
Edit persona component to work better with grid and show border on mobile
Update homepage styles to match new design and use new Grid component
Add hr to styles.css

style: update homepage and grid

---

packages/ui/src/lib/components/header-top.svelte

style: fix scroll shadow in dark mode

---

packages/ui/src/lib/components/button.svelte
packages/ui/src/routes/styles.css

Remove expand on hover
Update bg and border colors

style: update button to match new design

---

packages/ui/src/lib/components/chat.svelte
packages/ui/src/routes/(home)/chat/+page.svelte

Create Chat component
Update chat page to use Chat component

style: chats page

---

packages/ui/src/lib/adapters/in-memory-and-ipfs/utils.ts
packages/ui/src/lib/components/post.svelte
packages/ui/src/lib/utils/index.ts

Account for different amounts of images resizing accordingly 
Add 'additional images' icon to 6th image when it's not the last one

style: resize post images

---

packages/ui/src/lib/adapters/in-memory-and-ipfs/index.ts
packages/ui/src/routes/persona/draft/[id]/+page.svelte
packages/ui/src/routes/persona/new/+page.svelte

fix: erase draft persona after publishing

---

packages/ui/src/lib/components/icons/trash-can.svelte
packages/ui/src/lib/components/post_new.svelte
packages/ui/src/routes/persona/draft/[id]/+page.svelte

feat: enable editing and deleting seed posts

---

packages/ui/src/lib/adapters/in-memory-and-ipfs/index.ts
packages/ui/src/lib/adapters/index.ts
packages/ui/src/lib/adapters/zkitter/index.ts
packages/ui/src/routes/persona/draft/[id]/+page.svelte

Resolves #277 
I guess we can also close #272, right?

feat: delete draft persona

---

packages/ui/src/lib/adapters/in-memory-and-ipfs/index.ts
packages/ui/src/lib/constants.ts
packages/ui/src/routes/persona/[id]/post/new/+page.svelte

feat: prevent posting when minimal persona reputation is not met

---

packages/ui/src/lib/adapters/firebase/index.ts
packages/ui/src/lib/routes.ts
packages/ui/src/lib/stores/post.ts
packages/ui/src/routes/persona/[id]/pending/+page.svelte
packages/ui/src/routes/persona/[id]/pending/[postId]/+page.svelte
packages/ui/src/routes/persona/[id]/post/[postId]/+page.svelte

Resolves #311
Might help with #316

fix: clicking on a pending posts correctly links to it

---

packages/ui/src/routes/(home)/chat/+page.svelte
packages/ui/src/routes/persona/[id]/+page.svelte
packages/ui/src/routes/persona/[id]/pending/+page.svelte

feat: filtering and sorting

---

packages/ui/src/lib/components/chat-screen.svelte

fix: swap the chat bubble sides

---

packages/ui/src/lib/components/chat-screen.svelte
packages/ui/src/lib/components/textarea.svelte

fix: chat window - enter to send, remove image button, autoscroll

---

packages/ui/src/lib/adapters/firebase/index.ts
packages/ui/src/lib/adapters/in-memory-and-ipfs/index.ts
packages/ui/src/lib/adapters/index.ts
packages/ui/src/lib/adapters/zkitter/index.ts
packages/ui/src/routes/persona/draft/[id]/+page.svelte
packages/ui/src/routes/persona/new/+page.svelte

resolves #323, resolves #328, resolves #329

fix: create persona flow

---

packages/ui/src/routes/persona/draft/[id]/+page.svelte

fix: publishing a persona should add it to favorites

---

packages/ui/src/lib/adapters/firebase/index.ts
packages/ui/src/lib/adapters/in-memory-and-ipfs/index.ts
packages/ui/src/lib/adapters/index.ts
packages/ui/src/lib/adapters/zkitter/index.ts
packages/ui/src/routes/persona/[id]/pending/+page.svelte
packages/ui/src/routes/persona/[id]/post/new/+page.svelte

fix: creating post behavior and copy

---

packages/ui/src/routes/(home)/+layout.svelte

This was caused by some leftover dark mode css. All dark mode css should be commented out at this point.

style: fix homepage toggle bg color on dark mode

---

packages/ui/src/lib/components/post.svelte
packages/ui/src/lib/components/post_new.svelte

feat: correctly align images in create post and in viewing post

---

packages/ui/src/lib/components/icons/arrow-left.svelte
packages/ui/src/lib/components/post.svelte

feat: browse images in fullscreen

---

packages/ui/src/lib/adapters/firebase/index.ts

fix(firebase): update epoch counter

---

packages/ui/src/routes/(home)/+page.svelte
packages/ui/src/routes/persona/[id]/+page.svelte
packages/ui/src/routes/persona/[id]/pending/+page.svelte

feat: enable sorting and filtering even without being signed in

---

packages/ui/src/lib/components/post.svelte

fix: clicking on post image does not open the post but just shows the image in full screen

---

packages/ui/src/lib/components/header-top.svelte
packages/ui/src/lib/components/header.svelte
packages/ui/src/routes/persona/[id]/+page.svelte
packages/ui/src/routes/persona/[id]/pending/+page.svelte

Resolves #346
@sugarpusher please check this.
- There is probably a problem with the left & right spacing of buttons on the header. I was not sure how to fix it, there is some `inset`.

style: fix header animation to not be jumpy

---

packages/ui/src/lib/adapters/firebase/index.ts

feat: logout on metamask account change

---

.dockerignore
packages/relayer/Dockerfile
packages/relayer/package.json

This is already running on https://relayer.kurate.apyos.dev/

feat: add Dockerfile for relayer

---

packages/ui/src/routes/profile/+page.svelte

feat: show full address in profile

---

packages/ui/src/lib/adapters/firebase/index.ts
packages/ui/src/routes/persona/[id]/pending/[postId]/+page.svelte
packages/ui/src/routes/persona/[id]/post/[postId]/+page.svelte

fix: chat in firebase

---

packages/ui/src/lib/adapters/firebase/index.ts
packages/ui/src/lib/adapters/index.ts
packages/ui/src/lib/adapters/zkitter/index.ts
packages/ui/src/routes/persona/[id]/+page.svelte

fix(firebase): submit post

---

packages/ui/src/routes/persona/[id]/pending/+page.svelte
packages/ui/src/routes/persona/[id]/pending/[postId]/+page.svelte

fix: banner on pending posts when not connected

---

packages/ui/src/lib/components/post.svelte

feat: disable navigation on first an last image

---

packages/ui/src/routes/(home)/+page.svelte
packages/ui/src/routes/(home)/chat/+page.svelte
packages/ui/src/routes/persona/[id]/+page.svelte
packages/ui/src/routes/persona/[id]/pending/+page.svelte

feat: add sort personas by reputation

---

packages/ui/src/routes/styles.css

fix: stop all words from breaking
